name: 'Setup Development Environment'
description: 'Setup Nix, devenv, and install dependencies'
runs:
  using: 'composite'
  steps:
    - uses: cachix/install-nix-action@fc6e360bedc9ee72d75e701397f0bb30dce77568 # v31.5.2
    - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
      with:
        name: devenv
    - name: Cache npm
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        path: |
          ~/.npm
          node_modules
    - name: Install by devenv
      shell: bash
      run: |
        nix profile install nixpkgs#devenv
        devenv shell echo
    - name: Install npm packages
      shell: bash
      run: devenv shell npm ci
